name: Deploy the application to Google Cloud Run
on:
  push:
    branches:
      - 'master'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '277.0.0'
        service_account_key: ${{ secrets.GOOGLE_JSON_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - name: Configure gcloud
      run: |
        # Configure default project and region
        gcloud config set run/region ${{ secrets.GOOGLE_REGION }}
        gcloud config set project ${{ secrets.GOOGLE_PROJECT }}
      
    # Build the Docker image
    - name: Build & Publish
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GOOGLE_PROJECT }}/${{ secrets.APP_NAME }}
        
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy ${{ secrets.APP_NAME }} --quiet --image gcr.io/${{ secrets.GOOGLE_PROJECT }}/${{ secrets.APP_NAME }} --platform managed
